apiVersion: v1
kind: Service

metadata:
  name: web
  labels:
    app: web
    project: kubeforge

spec:
  type: NodePort

  selector:
    app: web

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
